### ISSUE TITLE
Add PyPi credentials to .travis.yml

### ISSUE THREAD

**Issue by jbeemster** [snowplow/release-manager#10]
- PYPI_USERNAME
- PYPI_PASSWORD

**Comment by alexanderdean** [comment]
Need to put the env vars you want in your description always

**Comment by jbeemster** [comment]
Done, sorry @alexanderdean!

**Comment by jbeemster** [comment]
Done differently, closing!

**Comment by alexanderdean** [comment]
Thanks!
