### ISSUE TITLE
Add FUNC resolver

### ISSUE THREAD

**Issue by jbeemster** [snowplow/release-manager#13]
As this tool will be used for a lot of SBT projects it would be good to bake in the functionality to grab an SBT project version.

```
sbt version -Dsbt.log.noformat=true | awk 'END{print}' | sed -r 's/\[info\]\s(.*)/\1/' | xargs echo -n
```

**Comment by jbeemster** [comment]
Has this been done already @chuwy ?

**Comment by chuwy** [comment]
Yes, I think so, @jbeemster if [implementation](https://github.com/snowplow/release-manager/blob/master/release_manager/utils.py#L100-L123) matches you vision.

**Comment by jbeemster** [comment]
Looks good to me!
