### ISSUE TITLE
Make division explicit

### ISSUE THREAD

**Issue by chuwy** [snowplow/release-manager#2]
In [Py3k](https://docs.python.org/3/howto/pyporting.html#division) division has different semantics. It returns exact float result, instead of integer floor.

So, [this](https://github.com/snowplow/release-manager/blob/master/release_manager.py#L91) code will be broken on python, since `301 / 3 != 3` anymore.

Use following import `from __future__ import division` and `//` operator.

**Comment by jbeemster** [comment]
Done, thanks for that @chuwy ... would never have thought about that!
