### ISSUE TITLE
Factor out requests

### ISSUE THREAD

**Issue by chuwy** [snowplow/release-manager#3]
[requests](http://docs.python-requests.org/en/master/) isn't in standard library and I think it's better to stay within stdlib. `urllib2` should work quite well for our purposes.

**Comment by chuwy** [comment]
Or we need to add it to `setup.py` requirements at least. 

If we're are going to factor out requests - we will have another simple approach to get started: `wget https://raw.githubusercontent.com/snowplow/release-manager/master/release_manager.py && ./release_manager.py`.

**Comment by jbeemster** [comment]
I have added it to setup.py .. doing large file uploads with urllib2 is a pain so would rather leave it in for the moment.  It also makes our code a lot more readable than with the standard libs for the same task.

**Comment by jbeemster** [comment]
Closing as we are going to keep requests.
