### ISSUE TITLE
Fix styling

### ISSUE THREAD

**Issue by chuwy** [snowplow/release-manager#5]
Hey @jbeemster! Everything looks great, below are very minor PEP8/pylint issues (we can skip them, except first one).
1. Wrong indentation in `parse_config` 6 instead of 8 spaces.
2. It is better to add `print_function` to import from `__future__`
3. In `raise ValueError("Invalid config passed to the program")` I think it would be nice to print traceback to give user a clue what exactly is wrong (if this traceback looks readable of course)
4. camelCase is unpythonic (`codeFamily`)
5. PEP8 [recommends](https://www.python.org/dev/peps/pep-0008/#blank-lines) to use two lines between functions (terribly minor)

**Comment by jbeemster** [comment]
1. Fixed!
2. Fixed!
3. It already prints the traceback, is there anyway to explicitly print it out?
4. Fixed!
5. Fixed!

Thanks @chuwy !

**Comment by chuwy** [comment]
3. Yes, but if we construct invalid YAML (starting with `{` for example) it will print:

```
 File "./release_manager.py", line 381, in <module>
    main()
  File "./release_manager.py", line 350, in main
    config = parse_config(args.config)
  File "./release_manager.py", line 273, in parse_config
    raise ValueError("Invalid config passed to the program")
ValueError: Invalid config passed to the program
```

But if we throw real exception, it would be more useful for user:

```
yaml.parser.ParserError: while parsing a flow mapping
  in "resources/config.yml", line 3, column 1
expected ',' or '}', but got ':'
  in "resources/config.yml", line 4, column 12
```

**Comment by jbeemster** [comment]
Oh sorry yes you are correct, have fixed that now!

**Comment by chuwy** [comment]
Then everything looks good for me!
